controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    miniarm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    miniarm_hand_controller:
      type: position_controllers/GripperActionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


miniarm_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - miniarm_joint1
      - miniarm_joint2
      - miniarm_joint3
      - miniarm_joint4
      - miniarm_joint5
      - miniarm_joint6

miniarm_hand_controller:
  ros__parameters:
    joint: miniarm_gripper_joint
